### ISSUE TITLE
Problem with nix build in the CRISPR folder on macOS

### ISSUE THREAD

**Issue by bierlingm** [holochain/CRISPR#107]
Not sure whether this is the right place and the right format, but I'm having trouble with building CRISPR on my macOS Catalina machine.

I've git cloned the repository and installed nix too. Then I run `nix build` but it results in this:

```error: unable to download 'https://cache.nixos.org/npgb26qnplym2v37wr863w0g77nhrm2d.narinfo': Problem with the SSL CA cert (path? access rights?) (77)```

**Comment by philipbeadle** [comment]
You should be using yarn to do any build actions.
And not ready yet will be soon
